In [15]:
import numpy as np
import pandas as pd

np.random.seed(42)

# pandas

## Sources

* [Intro to Machine Learning with TensorFlow](https://www.udacity.com/course/intro-to-machine-learning-with-tensorflow-nanodegree--nd230)
* [10 minutes to pandas](https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html)

## Example with DataFrame, Series from CSV

To load a `DataFrame` of life expectancy data from [Gapfinder](https://www.gapminder.org/):

In [98]:
bmi_life_data = pd.read_csv('../../data/bmi_and_life_expectancy.csv')
bmi_life_data.head()

Country  Life expectancy       BMI
0  Afghanistan             52.8  20.62058
1      Albania             76.8  26.44657
2      Algeria             75.5  24.59620
3      Andorra             84.6  27.63048
4       Angola             56.7  22.25083

To access a column as a `Series`:

In [17]:
a = bmi_life_data['BMI']
a.values[0:5,]

array([20.62058, 26.44657, 24.5962 , 27.63048, 22.25083])

If you want to change the shape of the `Series` so that every value is a separate array (e.g., to pass into scikit-learn):

In [18]:
a = bmi_life_data[['BMI']]
a.values[0:5,]

array([[20.62058],
       [26.44657],
       [24.5962 ],
       [27.63048],
       [22.25083]])

## Creating

Constructing a `Series` using array:

In [19]:
pd.Series([1, 3, 5, np.nan, 6, 8])

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

Constructing a `DataFrame` using array, with an index of dates:

In [43]:
dates = pd.date_range('20130101', periods=20)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06', '2013-01-07', '2013-01-08',
               '2013-01-09', '2013-01-10', '2013-01-11', '2013-01-12',
               '2013-01-13', '2013-01-14', '2013-01-15', '2013-01-16',
               '2013-01-17', '2013-01-18', '2013-01-19', '2013-01-20'],
              dtype='datetime64[ns]', freq='D')

In [44]:
df = pd.DataFrame(np.random.randn(20, 4), index=dates, columns=list('ABCD'))
df

A         B         C         D
2013-01-01  0.048522 -0.830950  0.270457 -0.050238
2013-01-02 -0.238948 -0.907564 -0.576771  0.755391
2013-01-03  0.500917 -0.977555  0.099332  0.751387
2013-01-04 -1.669405  0.543360 -0.662624  0.570599
2013-01-05 -0.763259 -1.804882 -1.627542  0.048085
2013-01-06  0.259723 -0.904317  0.638592 -1.661520
2013-01-07 -0.066080 -1.211016 -0.651836  0.047399
2013-01-08 -0.860413 -0.384556  1.006293 -0.576892
2013-01-09  0.835692 -1.129707  0.529804  1.441569
2013-01-10 -2.471645 -0.796895  0.577072 -0.203045
2013-01-11  0.371146 -0.603985  0.086590 -0.155677
2013-01-12  1.167782  0.254421  0.337603 -0.411877
2013-01-13 -0.487606 -0.432558  0.394452 -0.420984
2013-01-14  0.289775  2.075401  0.871125 -0.326024
2013-01-15  1.201214 -0.408075 -2.038125 -1.008086
2013-01-16 -1.870792 -0.351513  0.018418  1.676437
2013-01-17  0.326927 -0.219101  0.829406 -2.211135
2013-01-18  0.235615  0.770865 -1.478586  1.143754
2013-01-19  0.338496 -0.415288  0.632782  2.270693
2013-01-20  0.181866  0.248221 -0.459361 -0.849844

Constructing a `DataFrame` using dict:

In [45]:
df2 = pd.DataFrame({'A': 1.,
   ...:             'B': pd.Timestamp('20130102'),
   ...:             'C': pd.Series(1, index=list(range(4)), dtype='float32'),
   ...:             'D': np.array([3] * 4, dtype='int32'),
   ...:             'E': pd.Categorical(["test", "train", "test", "train"]),
   ...:             'F': 'foo'})
df2

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [46]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

## Viewing

View the first of last values in a dataframe:

In [47]:
df.head()

A         B         C         D
2013-01-01  0.048522 -0.830950  0.270457 -0.050238
2013-01-02 -0.238948 -0.907564 -0.576771  0.755391
2013-01-03  0.500917 -0.977555  0.099332  0.751387
2013-01-04 -1.669405  0.543360 -0.662624  0.570599
2013-01-05 -0.763259 -1.804882 -1.627542  0.048085

In [48]:
df.tail()

A         B         C         D
2013-01-16 -1.870792 -0.351513  0.018418  1.676437
2013-01-17  0.326927 -0.219101  0.829406 -2.211135
2013-01-18  0.235615  0.770865 -1.478586  1.143754
2013-01-19  0.338496 -0.415288  0.632782  2.270693
2013-01-20  0.181866  0.248221 -0.459361 -0.849844

In [49]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06', '2013-01-07', '2013-01-08',
               '2013-01-09', '2013-01-10', '2013-01-11', '2013-01-12',
               '2013-01-13', '2013-01-14', '2013-01-15', '2013-01-16',
               '2013-01-17', '2013-01-18', '2013-01-19', '2013-01-20'],
              dtype='datetime64[ns]', freq='D')

In [50]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [51]:
df.to_numpy()

array([[ 0.04852163, -0.83095012,  0.27045683, -0.05023811],
       [-0.23894805, -0.90756366, -0.57677133,  0.75539123],
       [ 0.50091719, -0.97755524,  0.09933231,  0.75138712],
       [-1.66940528,  0.54336019, -0.66262376,  0.57059867],
       [-0.76325916, -1.8048821 , -1.62754244,  0.04808495],
       [ 0.2597225 , -0.90431663,  0.63859246, -1.66152006],
       [-0.0660798 , -1.2110162 , -0.65183611,  0.04739867],
       [-0.86041337, -0.38455554,  1.00629281, -0.57689187],
       [ 0.83569211, -1.12970685,  0.52980418,  1.44156862],
       [-2.4716445 , -0.79689526,  0.57707213, -0.20304539],
       [ 0.37114587, -0.60398519,  0.08658979, -0.15567724],
       [ 1.16778206,  0.25442084,  0.33760266, -0.41187697],
       [-0.48760622, -0.43255819,  0.39445214, -0.42098448],
       [ 0.28977486,  2.0754008 ,  0.8711247 , -0.32602353],
       [ 1.20121392, -0.40807537, -2.03812454, -1.00808631],
       [-1.87079192, -0.35151348,  0.01841838,  1.67643731],
       [ 0.32692737, -0.

In [52]:
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

Summarize statistics of dataframe:

In [54]:
df.describe()

A          B          C          D
count  20.000000  20.000000  20.000000  20.000000
mean   -0.133524  -0.374285  -0.060146   0.041499
std     0.973838   0.847742   0.875578   1.100858
min    -2.471645  -1.804882  -2.038125  -2.211135
25%    -0.556519  -0.905128  -0.595538  -0.459961
50%     0.208740  -0.423923   0.184895  -0.102958
75%     0.346659  -0.102270   0.591000   0.752388
max     1.201214   2.075401   1.006293   2.270693

## Mutating
Transposing data:

In [55]:
df.T

2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06  \
A    0.048522   -0.238948    0.500917   -1.669405   -0.763259    0.259723   
B   -0.830950   -0.907564   -0.977555    0.543360   -1.804882   -0.904317   
C    0.270457   -0.576771    0.099332   -0.662624   -1.627542    0.638592   
D   -0.050238    0.755391    0.751387    0.570599    0.048085   -1.661520   

   2013-01-07  2013-01-08  2013-01-09  2013-01-10  2013-01-11  2013-01-12  \
A   -0.066080   -0.860413    0.835692   -2.471645    0.371146    1.167782   
B   -1.211016   -0.384556   -1.129707   -0.796895   -0.603985    0.254421   
C   -0.651836    1.006293    0.529804    0.577072    0.086590    0.337603   
D    0.047399   -0.576892    1.441569   -0.203045   -0.155677   -0.411877   

   2013-01-13  2013-01-14  2013-01-15  2013-01-16  2013-01-17  2013-01-18  \
A   -0.487606    0.289775    1.201214   -1.870792    0.326927    0.235615   
B   -0.432558    2.075401   -0.408075   -0.351513   -0.219101    0.770865   
C    0.394452    0.871125   -2.038125    0.018418    0.829406   -1.478586   
D   -0.420984   -0.326024   -1.008086    1.676437   -2.211135    1.143754   

   2013-01-19  2013-01-20  
A    0.338496    0.181866  
B   -0.415288    0.248221  
C    0.632782   -0.459361  
D    2.270693   -0.849844

Sorting rows by keys:

In [63]:
df.sort_index(axis=0, ascending=False).head()

A         B         C         D
2013-01-20  0.181866  0.248221 -0.459361 -0.849844
2013-01-19  0.338496 -0.415288  0.632782  2.270693
2013-01-18  0.235615  0.770865 -1.478586  1.143754
2013-01-17  0.326927 -0.219101  0.829406 -2.211135
2013-01-16 -1.870792 -0.351513  0.018418  1.676437

Sorting columns:

In [64]:
df.sort_index(axis=1, ascending=True).head()

A         B         C         D
2013-01-01  0.048522 -0.830950  0.270457 -0.050238
2013-01-02 -0.238948 -0.907564 -0.576771  0.755391
2013-01-03  0.500917 -0.977555  0.099332  0.751387
2013-01-04 -1.669405  0.543360 -0.662624  0.570599
2013-01-05 -0.763259 -1.804882 -1.627542  0.048085

Sorting rows by values:

In [66]:
df.sort_values(by='B')

A         B         C         D
2013-01-05 -0.763259 -1.804882 -1.627542  0.048085
2013-01-07 -0.066080 -1.211016 -0.651836  0.047399
2013-01-09  0.835692 -1.129707  0.529804  1.441569
2013-01-03  0.500917 -0.977555  0.099332  0.751387
2013-01-02 -0.238948 -0.907564 -0.576771  0.755391
2013-01-06  0.259723 -0.904317  0.638592 -1.661520
2013-01-01  0.048522 -0.830950  0.270457 -0.050238
2013-01-10 -2.471645 -0.796895  0.577072 -0.203045
2013-01-11  0.371146 -0.603985  0.086590 -0.155677
2013-01-13 -0.487606 -0.432558  0.394452 -0.420984
2013-01-19  0.338496 -0.415288  0.632782  2.270693
2013-01-15  1.201214 -0.408075 -2.038125 -1.008086
2013-01-08 -0.860413 -0.384556  1.006293 -0.576892
2013-01-16 -1.870792 -0.351513  0.018418  1.676437
2013-01-17  0.326927 -0.219101  0.829406 -2.211135
2013-01-20  0.181866  0.248221 -0.459361 -0.849844
2013-01-12  1.167782  0.254421  0.337603 -0.411877
2013-01-04 -1.669405  0.543360 -0.662624  0.570599
2013-01-18  0.235615  0.770865 -1.478586  1.143754
2013-01-14  0.289775  2.075401  0.871125 -0.326024

## Getting

In [67]:
df['A']

2013-01-01    0.048522
2013-01-02   -0.238948
2013-01-03    0.500917
2013-01-04   -1.669405
2013-01-05   -0.763259
2013-01-06    0.259723
2013-01-07   -0.066080
2013-01-08   -0.860413
2013-01-09    0.835692
2013-01-10   -2.471645
2013-01-11    0.371146
2013-01-12    1.167782
2013-01-13   -0.487606
2013-01-14    0.289775
2013-01-15    1.201214
2013-01-16   -1.870792
2013-01-17    0.326927
2013-01-18    0.235615
2013-01-19    0.338496
2013-01-20    0.181866
Freq: D, Name: A, dtype: float64

In [68]:
df[0:3]

A         B         C         D
2013-01-01  0.048522 -0.830950  0.270457 -0.050238
2013-01-02 -0.238948 -0.907564 -0.576771  0.755391
2013-01-03  0.500917 -0.977555  0.099332  0.751387

In [69]:
df['20130102':'20130104']

A         B         C         D
2013-01-02 -0.238948 -0.907564 -0.576771  0.755391
2013-01-03  0.500917 -0.977555  0.099332  0.751387
2013-01-04 -1.669405  0.543360 -0.662624  0.570599

## Slicing by label

In [75]:
dates[0]

Timestamp('2013-01-01 00:00:00', freq='D')

In [76]:
df.loc[dates[0]]

A    0.048522
B   -0.830950
C    0.270457
D   -0.050238
Name: 2013-01-01 00:00:00, dtype: float64

In [77]:
df.loc['2013-01-01']

A    0.048522
B   -0.830950
C    0.270457
D   -0.050238
Name: 2013-01-01 00:00:00, dtype: float64

In [78]:
df.loc[:, ['A', 'B']].head()

A         B
2013-01-01  0.048522 -0.830950
2013-01-02 -0.238948 -0.907564
2013-01-03  0.500917 -0.977555
2013-01-04 -1.669405  0.543360
2013-01-05 -0.763259 -1.804882

In [79]:
df.loc['20130102':'20130104', ['A', 'B']]

A         B
2013-01-02 -0.238948 -0.907564
2013-01-03  0.500917 -0.977555
2013-01-04 -1.669405  0.543360

Note reduction in dimensions:

In [80]:
df.loc[dates[0], 'A']

0.04852162794482699

## Slicing by index

In [81]:
df.iloc[3]

A   -1.669405
B    0.543360
C   -0.662624
D    0.570599
Name: 2013-01-04 00:00:00, dtype: float64

In [82]:
df.iloc[3:5, 0:2]

A         B
2013-01-04 -1.669405  0.543360
2013-01-05 -0.763259 -1.804882

In [83]:
df.iloc[[1, 2, 4], [0, 2]]

A         C
2013-01-02 -0.238948 -0.576771
2013-01-03  0.500917  0.099332
2013-01-05 -0.763259 -1.627542

In [84]:
df.iloc[1:3, :]

A         B         C         D
2013-01-02 -0.238948 -0.907564 -0.576771  0.755391
2013-01-03  0.500917 -0.977555  0.099332  0.751387

In [85]:
df.iloc[1, 1]

-0.9075636620415979

## Boolean indexing

In [86]:
df[df['A'] > 0]

A         B         C         D
2013-01-01  0.048522 -0.830950  0.270457 -0.050238
2013-01-03  0.500917 -0.977555  0.099332  0.751387
2013-01-06  0.259723 -0.904317  0.638592 -1.661520
2013-01-09  0.835692 -1.129707  0.529804  1.441569
2013-01-11  0.371146 -0.603985  0.086590 -0.155677
2013-01-12  1.167782  0.254421  0.337603 -0.411877
2013-01-14  0.289775  2.075401  0.871125 -0.326024
2013-01-15  1.201214 -0.408075 -2.038125 -1.008086
2013-01-17  0.326927 -0.219101  0.829406 -2.211135
2013-01-18  0.235615  0.770865 -1.478586  1.143754
2013-01-19  0.338496 -0.415288  0.632782  2.270693
2013-01-20  0.181866  0.248221 -0.459361 -0.849844

In [87]:
df[df > 0]

A         B         C         D
2013-01-01  0.048522       NaN  0.270457       NaN
2013-01-02       NaN       NaN       NaN  0.755391
2013-01-03  0.500917       NaN  0.099332  0.751387
2013-01-04       NaN  0.543360       NaN  0.570599
2013-01-05       NaN       NaN       NaN  0.048085
2013-01-06  0.259723       NaN  0.638592       NaN
2013-01-07       NaN       NaN       NaN  0.047399
2013-01-08       NaN       NaN  1.006293       NaN
2013-01-09  0.835692       NaN  0.529804  1.441569
2013-01-10       NaN       NaN  0.577072       NaN
2013-01-11  0.371146       NaN  0.086590       NaN
2013-01-12  1.167782  0.254421  0.337603       NaN
2013-01-13       NaN       NaN  0.394452       NaN
2013-01-14  0.289775  2.075401  0.871125       NaN
2013-01-15  1.201214       NaN       NaN       NaN
2013-01-16       NaN       NaN  0.018418  1.676437
2013-01-17  0.326927       NaN  0.829406       NaN
2013-01-18  0.235615  0.770865       NaN  1.143754
2013-01-19  0.338496       NaN  0.632782  2.270693
2013-01-20  0.181866  0.248221       NaN       NaN

In [89]:
df2 = df.copy()
df2['E'] = ['one', 'one', 'two', 'three', 'four', 'three', 'two', 'one', 'four', 'four'] * 2
df2

A         B         C         D      E
2013-01-01  0.048522 -0.830950  0.270457 -0.050238    one
2013-01-02 -0.238948 -0.907564 -0.576771  0.755391    one
2013-01-03  0.500917 -0.977555  0.099332  0.751387    two
2013-01-04 -1.669405  0.543360 -0.662624  0.570599  three
2013-01-05 -0.763259 -1.804882 -1.627542  0.048085   four
2013-01-06  0.259723 -0.904317  0.638592 -1.661520  three
2013-01-07 -0.066080 -1.211016 -0.651836  0.047399    two
2013-01-08 -0.860413 -0.384556  1.006293 -0.576892    one
2013-01-09  0.835692 -1.129707  0.529804  1.441569   four
2013-01-10 -2.471645 -0.796895  0.577072 -0.203045   four
2013-01-11  0.371146 -0.603985  0.086590 -0.155677    one
2013-01-12  1.167782  0.254421  0.337603 -0.411877    one
2013-01-13 -0.487606 -0.432558  0.394452 -0.420984    two
2013-01-14  0.289775  2.075401  0.871125 -0.326024  three
2013-01-15  1.201214 -0.408075 -2.038125 -1.008086   four
2013-01-16 -1.870792 -0.351513  0.018418  1.676437  three
2013-01-17  0.326927 -0.219101  0.829406 -2.211135    two
2013-01-18  0.235615  0.770865 -1.478586  1.143754    one
2013-01-19  0.338496 -0.415288  0.632782  2.270693   four
2013-01-20  0.181866  0.248221 -0.459361 -0.849844   four

In [90]:
df2[df2['E'].isin(['two', 'four'])]

A         B         C         D     E
2013-01-03  0.500917 -0.977555  0.099332  0.751387   two
2013-01-05 -0.763259 -1.804882 -1.627542  0.048085  four
2013-01-07 -0.066080 -1.211016 -0.651836  0.047399   two
2013-01-09  0.835692 -1.129707  0.529804  1.441569  four
2013-01-10 -2.471645 -0.796895  0.577072 -0.203045  four
2013-01-13 -0.487606 -0.432558  0.394452 -0.420984   two
2013-01-15  1.201214 -0.408075 -2.038125 -1.008086  four
2013-01-17  0.326927 -0.219101  0.829406 -2.211135   two
2013-01-19  0.338496 -0.415288  0.632782  2.270693  four
2013-01-20  0.181866  0.248221 -0.459361 -0.849844  four

## Operations

Mean of columns:

In [92]:
df.mean()

A   -0.133524
B   -0.374285
C   -0.060146
D    0.041499
dtype: float64

Mean of rows:

In [94]:
df.mean(1)

2013-01-01   -0.140552
2013-01-02   -0.241973
2013-01-03    0.093520
2013-01-04   -0.304518
2013-01-05   -1.036900
2013-01-06   -0.416880
2013-01-07   -0.470383
2013-01-08   -0.203892
2013-01-09    0.419340
2013-01-10   -0.723628
2013-01-11   -0.075482
2013-01-12    0.336982
2013-01-13   -0.236674
2013-01-14    0.727569
2013-01-15   -0.563268
2013-01-16   -0.131862
2013-01-17   -0.318476
2013-01-18    0.167912
2013-01-19    0.706671
2013-01-20   -0.219780
Freq: D, dtype: float64

In [95]:
df.apply(np.cumsum)

A         B         C         D
2013-01-01  0.048522 -0.830950  0.270457 -0.050238
2013-01-02 -0.190426 -1.738514 -0.306315  0.705153
2013-01-03  0.310491 -2.716069 -0.206982  1.456540
2013-01-04 -1.358915 -2.172709 -0.869606  2.027139
2013-01-05 -2.122174 -3.977591 -2.497148  2.075224
2013-01-06 -1.862451 -4.881908 -1.858556  0.413704
2013-01-07 -1.928531 -6.092924 -2.510392  0.461102
2013-01-08 -2.788944 -6.477479 -1.504099 -0.115789
2013-01-09 -1.953252 -7.607186 -0.974295  1.325779
2013-01-10 -4.424897 -8.404081 -0.397223  1.122734
2013-01-11 -4.053751 -9.008067 -0.310633  0.967057
2013-01-12 -2.885969 -8.753646  0.026970  0.555180
2013-01-13 -3.373575 -9.186204  0.421422  0.134195
2013-01-14 -3.083800 -7.110803  1.292546 -0.191828
2013-01-15 -1.882586 -7.518879 -0.745578 -1.199915
2013-01-16 -3.753378 -7.870392 -0.727160  0.476523
2013-01-17 -3.426451 -8.089493  0.102246 -1.734613
2013-01-18 -3.190836 -7.318627 -1.376340 -0.590859
2013-01-19 -2.852340 -7.733915 -0.743559  1.679834
2013-01-20 -2.670474 -7.485695 -1.202919  0.829990

In [96]:
df.apply(lambda x: x.max() - x.min())

A    3.672858
B    3.880283
C    3.044417
D    4.481828
dtype: float64