In [1]:
import numpy as np

# ndarray

Based on the [numpy quickstart tutorial](https://docs.scipy.org/doc/numpy/user/quickstart.html).

## Properties

In [3]:
data = np.loadtxt('../data/random-ints-to-floats.csv', delimiter = ',') # ndarray (aka, array)
data.ndim

2

In [4]:
data.shape

(10, 2)

In [5]:
data.size

20

In [6]:
data.dtype

dtype('float64')

## Creation

In [7]:
data2 = np.array([0,1,2,3,4,5,6,7,8,9]).reshape(2,5)
data2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
np.array( [ [1,2.2], [3.7,'4'] ], dtype=int) # Explicitly state datatype

array([[1, 2],
       [3, 4]])

In [10]:
# Growing arrays is expensive, so allocate upfront if size is known
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.arange( 0, 2, 0.3 )  # start (inclusive), stop (exclusive), step size

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [13]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [14]:
np.linspace( 0, 1, 5 ) # start (inclusive), stop (inclusive), number of elements

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [15]:
np.fromfunction(lambda x, y: 10*x+y, (5,4), dtype=int)

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

## Basic Binary Operations

In [16]:
a = np.arange(10,50,10)
b = np.ones(4,dtype=int)
print(a)
print(b)

[10 20 30 40]
[1 1 1 1]


In [17]:
a + b

array([11, 21, 31, 41])

In [18]:
a - b

array([ 9, 19, 29, 39])

In [19]:
a**2

array([ 100,  400,  900, 1600])

In [20]:
a * 2

array([20, 40, 60, 80])

In [21]:
a <= 20

array([ True,  True, False, False])

In [22]:
c = np.copy(a) # Copy an array
c += 1 # modifies in-place
print(c)
print(a)

[11 21 31 41]
[10 20 30 40]


In [23]:
d = np.array([ [1,1], [0,1] ])
e = np.array([ [2,0], [3,4] ])

In [72]:
d * e # element-wise multiplication

array([[2, 0],
       [0, 4]])

In [73]:
d.dot(e)

array([[5, 4],
       [3, 4]])

In [25]:
d @ e # dot product

array([[5, 4],
       [3, 4]])

In [26]:
d.dot(e) # same as @

array([[5, 4],
       [3, 4]])

## Basic Unary Operations

In [27]:
a = np.linspace(1,3,5)
a

array([1. , 1.5, 2. , 2.5, 3. ])

In [28]:
a.sum()

10.0

In [29]:
a.min()

1.0

In [30]:
a.max()

3.0

In [31]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
b.sum()

66

In [33]:
b.sum(axis=0) # sum each column

array([12, 15, 18, 21])

In [34]:
b.min(axis=1) # sum each row

array([0, 4, 8])

## Indexing, slicing, iterating

In [35]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [36]:
a[2:5]

array([2, 3, 4])

In [37]:
a[2:5] *= 2
a

array([ 0,  1,  4,  6,  8,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [38]:
a = np.arange(15)
a[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [39]:
b = np.fromfunction(lambda x, y: 10*x+y, (5,4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [40]:
b[2,3]

23

In [41]:
b[0:5, 1]

array([ 1, 11, 21, 31, 41])

In [42]:
b[:,1]

array([ 1, 11, 21, 31, 41])

In [43]:
b[1,:]

array([10, 11, 12, 13])

In [44]:
b[1]

array([10, 11, 12, 13])

In [45]:
b[1,...]

array([10, 11, 12, 13])

In [46]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [47]:
for ele in b.flat:
    print(ele)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


## Changing Shape

In [48]:
a = np.floor(10*np.random.random((3,4)))
a

array([[2., 3., 0., 7.],
       [5., 9., 2., 4.],
       [0., 7., 1., 1.]])

In [49]:
a.shape

(3, 4)

In [50]:
a.ravel() # flatten

array([2., 3., 0., 7., 5., 9., 2., 4., 0., 7., 1., 1.])

In [51]:
a.reshape(6,2)

array([[2., 3.],
       [0., 7.],
       [5., 9.],
       [2., 4.],
       [0., 7.],
       [1., 1.]])

In [52]:
a.T # transpose

array([[2., 5., 0.],
       [3., 9., 7.],
       [0., 2., 1.],
       [7., 4., 1.]])

## Stacking

In [53]:
a = np.floor(10*np.random.random((2,2)))
a

array([[7., 4.],
       [7., 0.]])

In [54]:
b = np.floor(10*np.random.random((2,2)))
b

array([[9., 8.],
       [2., 1.]])

In [55]:
np.vstack((a,b))

array([[7., 4.],
       [7., 0.],
       [9., 8.],
       [2., 1.]])

In [56]:
np.hstack((a,b))

array([[7., 4., 9., 8.],
       [7., 0., 2., 1.]])

## Splitting

In [57]:
a = np.floor(10*np.random.random((2,12)))
a

array([[2., 5., 7., 8., 8., 7., 7., 3., 7., 5., 1., 7.],
       [3., 4., 0., 2., 2., 9., 5., 4., 9., 3., 4., 2.]])

In [58]:
np.hsplit(a,3)

[array([[2., 5., 7., 8.],
        [3., 4., 0., 2.]]),
 array([[8., 7., 7., 3.],
        [2., 9., 5., 4.]]),
 array([[7., 5., 1., 7.],
        [9., 3., 4., 2.]])]

In [59]:
np.vsplit(a,2)

[array([[2., 5., 7., 8., 8., 7., 7., 3., 7., 5., 1., 7.]]),
 array([[3., 4., 0., 2., 2., 9., 5., 4., 9., 3., 4., 2.]])]

In [60]:
np.hsplit(a,(3,4))  # Split after 3rd & 4th cols

[array([[2., 5., 7.],
        [3., 4., 0.]]),
 array([[8.],
        [2.]]),
 array([[8., 7., 7., 3., 7., 5., 1., 7.],
        [2., 9., 5., 4., 9., 3., 4., 2.]])]

## Misc

In [61]:
np.isscalar([1,2,3])

False

In [74]:
np.isscalar('abc')

True